import { MODELS } from '../ollama/modelConfig';
import { generateCompletion } from '../ollama/ollamaClient'; // Assume this exists

export interface PlanStep {
    step: number;
    action: string;
    description: string;
}

export interface ExecutionPlan {
    plan: PlanStep[];
}

/**
 * Planner Agent
 * Breaks a high-level user task into clear, executable steps mapped to available tools.
 * Uses the reasoning model (phi3) configured for JSON output.
 */
export async function createPlan(task: string, context?: any): Promise<ExecutionPlan> {
    const systemPrompt = `
You are an expert AI Planner Agent (similar to OpenClaw/Kimi).
Your job is to break down the user's task into a sequential, logical execution plan.
You must map each step to a specific, actionable tool/action.

Available Actions:
- web_search
- browser_open
- job_portal_search
- assignment_executor
- code_runner
- data_aggregator

You MUST respond in strictly valid JSON matching this schema:
{
  "plan": [
    {
      "step": <number>,
      "action": "<action_name>",
      "description": "<what this step accomplishes>"
    }
  ]
}
`.trim();

    const prompt = `Task: ${task}\nContext: ${JSON.stringify(context || {})}\nOutput JSON plan only.`;

    try {
        const responseText = await generateCompletion({
            model: MODELS.REASONING,
            system: systemPrompt,
            prompt: prompt,
            format: 'json',
            temperature: 0.1, // Low temperature for deterministic planning
        });

        const planData = JSON.parse(responseText);

        // Validate schema
        if (!planData.plan || !Array.isArray(planData.plan)) {
            throw new Error("Invalid plan generated by model");
        }

        return planData as ExecutionPlan;
    } catch (error) {
        console.error("Planner Agent failed:", error);
        // Fallback or bubble up
        throw new Error(`Failed to generate task plan: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
}
